name: Container Build Pipeline
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Secure Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Container
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/automated-challenge:v2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/automated-challenge:v2